languageCode = "ru"
languageName = "Русский"
languageDirection = "ltr"
weight = 2

title = "Данила Николаев"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  description = "Website of Danila Nikolaev aka dartungar"

[params.author]
  name = "Данила Николаев"
  image = "/img/avatar.png"
  headline = "cоздаю, программирую, познаю"
  bio = "Danila Nikolaev is a nomad software engineer."
  links = [
     { email = "mailto:dartungar@gmail.com" },
     { github = "https://github.com/dartungar" },
     { linkedin = "https://linkedin.com/in/dartungar" },
     { telegram = "https://t.me/dartungar" },
  ]